/*
 * File: app/view/AttachmentUnit.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.AttachmentUnit', {
    extend: 'Ext.container.Container',
    alias: 'widget.attachmentunit',

    requires: [
        'TaskManager.view.AttachmentUnitViewModel',
        'Ext.container.Container'
    ],

    viewModel: {
        type: 'attachmentunit'
    },
    html: '<iframe id="downFrame" style="display:none"></iframe>',
    margin: '0 10 0 0',

    items: [
        {
            xtype: 'container',
            itemId: 'imageCon',
            margin: '0 8 0 0',
            padding: 8,
            style: 'border:1px solid #cecece;text-align:center',
            width: 'auto',
            autoDestroy: false,
            layout: 'column'
        }
    ],

    addImage: function(imgInfo, index) {
        var ic = this.down('#imageCon');
        var src = imgInfo.thumb_path;
        ic.on('render', function(){
            ic.el.on('click', function(){
                var viewer = ic.up('#docViewer');
                var idx = viewer.getViewModel().data.bd_idx;
                if(imgInfo.isImage){
                    var win = window.open('', 'Image View');
                    win.document.write('<img src="' + imgInfo.file_path + '"/>');
                }
                else{
                    var iframe = document.getElementById('downFrame');
                    iframe.src =imgInfo.file_path;
                }
            });
        });
        var imgConH = 100;
        var imgH = imgConH;
        var fs = getController('Main').bytesToSize(imgInfo.file_size);
        var fw = imgInfo.file_width;
        var fh = imgInfo.file_height;
        if(fh < imgConH){
            imgH = fh;
        }
        var htmlImg = '<div style="width:100%;"><img style="height:'+ imgH +'px" src=' + src + '></div>';
        htmlImg += '<span style="margin-top:10px;width:100%;font-size:11px">' + imgInfo.file_name + '<br>' + fs + '</span>';
        ic.setHtml(htmlImg);
    }

});