/*
 * File: app/view/DatasetGridBox.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.DatasetGridBox', {
    extend: 'Ext.container.Container',
    alias: 'widget.datasetgridbox',

    requires: [
        'TaskManager.view.DatasetGridBoxViewModel',
        'Ext.form.Label',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CheckboxModel'
    ],

    viewModel: {
        type: 'datasetgridbox'
    },
    width: '100%',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            itemId: 'datasetHeader',
            layout: {
                type: 'hbox',
                align: 'bottom'
            },
            items: [
                {
                    xtype: 'label',
                    cls: 'x-form-item-label-default',
                    itemId: 'title'
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                },
                {
                    xtype: 'button',
                    height: 24,
                    itemId: 'btnAddColumn',
                    margin: '0 2 0 0',
                    ui: 'plain-toolbar-small',
                    width: 24,
                    icon: 'resources/images/ico_plus.png',
                    bind: {
                        tooltip: '{addRow}'
                    }
                },
                {
                    xtype: 'button',
                    height: 24,
                    itemId: 'btnDelColumn',
                    margin: '0 2 0 0',
                    ui: 'plain-toolbar-small',
                    width: 24,
                    icon: 'resources/images/ico_minus.png',
                    bind: {
                        tooltip: '{delRow}'
                    }
                },
                {
                    xtype: 'button',
                    height: 24,
                    itemId: 'btnDelAllColumn',
                    margin: '0 8 0 0',
                    ui: 'plain-toolbar-small',
                    width: 24,
                    icon: 'resources/images/ico_delete.png',
                    bind: {
                        tooltip: '{delAllRow}'
                    }
                }
            ]
        },
        {
            xtype: 'gridpanel',
            dataIdx: '',
            colsInfo: [
                
            ],
            cls: 'datasetGrid',
            itemId: 'datasetGrid',
            header: false,
            enableColumnHide: false,
            enableColumnMove: false,
            columns: [
                {
                    xtype: 'gridcolumn',
                    draggable: false,
                    sortable: false,
                    dataIndex: 'string',
                    text: 'String',
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 1
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],

    addTitle: function(title) {
        var lb = this.down('#title');
        lb.setText(title);
    },

    getGrid: function() {
        return this.down('#datasetGrid');
    }

});