/*
 * File: app/view/FormSpacer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.FormSpacer', {
    extend: 'Ext.toolbar.Spacer',
    alias: 'widget.formspacer',

    requires: [
        'TaskManager.view.FormSpacerViewModel'
    ],

    viewModel: {
        type: 'formspacer'
    },
    height: 1,
    style: 'border-top:1px solid #e9e9e9',
    width: '100%'

});