/*
 * File: app/view/MyBarChart.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.MyBarChart', {
    extend: 'Ext.chart.CartesianChart',
    alias: 'widget.mybarchart',

    requires: [
        'TaskManager.view.MyBarChartViewModel',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'mybarchart'
    },
    colors: [
        '#115fa6',
        '#94ae0a',
        '#a61120',
        '#ff8809',
        '#ffd13e',
        '#a61187',
        '#24ad9a',
        '#7c7474',
        '#a66111'
    ],

    axes: [
        {
            type: 'category',
            fields: [
                'x'
            ],
            position: 'bottom'
        },
        {
            type: 'numeric',
            fields: [
                'y1',
                'y2',
                'y3'
            ],
            grid: {
                odd: {
                    fill: '#e8e8e8'
                }
            },
            position: 'left'
        }
    ],
    series: [
        {
            type: 'bar',
            xField: 'x',
            yField: [
                'y1',
                'y2',
                'y3'
            ]
        }
    ],
    interactions: [
        {
            type: 'panzoom'
        }
    ]

});