/*
 * File: app/view/MyTabPanel1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.MyTabPanel1', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel1',

    requires: [
        'TaskManager.view.MyTabPanel1ViewModel',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'mytabpanel1'
    },
    height: 250,
    width: 400,
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            closable: true,
            title: 'Tab 1'
        }
    ]

});