/*
 * File: app/view/ShortcutEditWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.ShortcutEditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.shortcuteditwindow',

    requires: [
        'TaskManager.view.ShortcutEditWindowViewModel',
        'Ext.container.Container'
    ],

    viewModel: {
        type: 'shortcuteditwindow'
    },
    height: 600,
    padding: 20,
    scrollable: true,
    width: 800,

    bind: {
        title: '{changeShortcut}'
    },
    items: [
        {
            xtype: 'container',
            height: '100%',
            itemId: 'shortcutCon',
            width: '100%',
            layout: 'column'
        }
    ]

});