/*
 * File: app/view/Viewer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.Viewer', {
    extend: 'Ext.container.Container',
    alias: 'widget.viewer',

    requires: [
        'TaskManager.view.ViewerViewModel'
    ],

    config: {
        editable: false,
        categoryId: '',
        record: null
    },

    viewModel: {
        type: 'viewer'
    },
    height: '100%',
    itemId: 'viewer',
    padding: '0 0 30 0',
    width: '100%',
    layout: 'fit'

});