/*
 * File: app/model/CategoryModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.model.CategoryModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            mapping: 'title',
            name: 'text'
        },
        {
            name: 'lazy'
        },
        {
            mapping: 'data.id',
            name: 'id'
        },
        {
            convert: function(v, rec) {
                return (rec.get('lazy') === false);
            },
            name: 'leaf'
        },
        {
            name: 'title'
        },
        {
            mapping: 'data.code',
            name: 'code'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'isShortcut'
        }
    ]
});