/*
 * File: app/model/FieldModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.model.FieldModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            convert: function(v, rec) {
                var value;
                if(rec.get('cols_type') == 'colorchk'){
                    value = [];
                    var val;
                    for(var i=0; i<v.length; i++){
                        val = v[i].split('||');
                        value.push([val[1], val[0], v[i]]);
                    }
                }
                else{
                    value = v;
                }
                return value;
            },
            name: 'cols_data'
        },
        {
            name: 'cols_idx'
        },
        {
            name: 'cols_name'
        },
        {
            name: 'cols_type'
        }
    ]
});