/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.LoadMask',
        'Ext.ux.exporter.Exporter',
        'TaskManager.doc.Viewer'
    ],
    models: [
        'FieldModel',
        'CategoryModel',
        'UpModel'
    ],
    stores: [
        'FieldStore',
        'CategoryStore',
        'ShortcutsStore'
    ],
    views: [
        'MainView',
        'AttachmentUnit',
        'LoginWindow',
        'NewRequest',
        'DatasetGridBox',
        'MultiSelectWindow',
        'LinkedData',
        'LinkingWindow',
        'Preference',
        'Shortcut',
        'ShortcutEditWindow',
        'Viewer',
        'DataGroupWindow',
        'FormSpacer',
        'MultiFileInput',
        'MyTabPanel1',
        'LinkUnit'
    ],
    controllers: [
        'Login',
        'Main',
        'Search',
        'Upload',
        'Config',
        'Viewer'
    ],
    name: 'TaskManager',

    launch: function() {
        Ext.create('TaskManager.view.MainView');
        app = TaskManager;
    }

});
