/*
 * File: app/controller/Search.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.controller.Search', {
    extend: 'Ext.app.Controller',

    refs: {
        fdSearchAll: '#fdSearchAll'
    },

    control: {
        "#findIt": {
            click: 'onFindItClick'
        },
        "#findDetail": {
            click: 'onFindDetailClick'
        }
    },

    onFindItClick: function() {
        var val = this.getFdSearchAll().getValue();
        var query = '&ca_id='+ selectedCategory +'&se_all=' + val  + '&page=1';
        this.search(query, Ext.getStore('dStore_' + selectedCategory));
    },

    onFindDetailClick: function() {

    },

    search: function(query, store) {
        var me = this;
        var dataUrl = getDataListByIdApi(query);
        store.getProxy().setUrl(dataUrl);
        store.load();
    },

    getSearchIdx: function(value) {
        value = value.toString();
        if(value.length == 1){
            value = '000' + value;
        }
        if(value.length == 2){
            value = '00' + value;
        }
        if(value.length == 3){
            value = '0' + value;
        }

        return value;
    }

});
